version: '3.8'
services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

volumes:
  jenkins_home:

networks:
  app-network:
    external: true